
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: election
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/election
      - JWT_SECRET=supers3cr3t_bde_el3ct1on_k3y
    depends_on:
      - db
    volumes:
      - ./backend/prisma:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
